### ISSUE TITLE
Divine super defence

### ISSUE THREAD

**Issue by Stickaplex** [AnkouOSRS/unpotted-reminder#9]
Just got the plugin (ty btw) and was fiddling around testing it with divine super def but it doesn't work. Not that I plan to use it on those just was testing the settings for it.

Just thought it was something you should be aware of after reading a different thread

**Comment by AnkouOSRS** [comment]
Currently if you're training defence using melee the plugin will instead check if you have a potion that boosts **strength**, as well as if your **strength** stat is above your threshold. This is intentional since boosting strength is far more important when training melee.

Because of this it would be pointless to add potions that only boost defence, though I would be open to changing the plugin so that it checks your defence boost as well as strength if people would find that useful.
